### ISSUE TITLE
FAIL sox: missing filename

### ISSUE THREAD

**Issue by michaelKurowski** [RedKenrok/node-audiorecorder#10]
```
// Import module.
const AudioRecorder = require('node-audiorecorder');
 
// Options is an optional parameter for the constructor call.
// If an option is not given the default value, as seen below, will be used.
const options = {
  program: `sox`,     // Which program to use, either `arecord`, `rec`, or `sox`.
  device: '"Realtek High Definition Audio"'
};
// Optional parameter intended for debugging.
// The object has to implement a log and warn function.
const logger = console;
 
// Create an instance.
let audioRecorder = new AudioRecorder(options, logger);

audioRecorder.start();
audioRecorder.stream();
```
Hello, for above code I'm getting:
`FAIL sox: missing filename`
This is the command generated by node-audiorecorder:
`sox -q -c 1 -r 16000 -t wav -d "Realtek High Definition Audio" -V0 -L -b 16 -e signed-integer - silence -l 1 0.1 0.5% 1 2.0 0.5%`
Sox version is 14.4.1 (I've also tried 14.4.2 to no success, the result is the same).
Windows 10 Home (10.0.18362)
Node version: v12.13.0
node audiorecorder: 1.4.1

**Comment by RedKenrok** [comment]
I'm unable to replicate your error, however what I do notice is the line `device: '"Realtek High Definition Audio"'`. Could you try running the script without that line of code I think the name might be incorrect. Otherwise cloning this repository and run the two examples using the commands `node examples/print-command.js` and `node examples/record-to-file.js`.

**Comment by michaelKurowski** [comment]
I'm getting that there's no default adio device without that line.

**Comment by Twiggeh** [comment]
@michaelKurowski Use a number (from 0 to ...) instead of the name :)
