### ISSUE TITLE
What type of data is returned / how to send it | Settings for Sox | Child process not getting killed

### ISSUE THREAD

**Issue by Twiggeh** [RedKenrok/node-audiorecorder#12]
Hi !
Thank you for making this module :) 

When I tried using it, I had a couple of sox errors, maybe you can include them in your troubleshooting ? (I am a noob, not sure if these are proper or even viable fixes)

Win 10, Node 10.15.3, sox 4.4.2 & 4.4.1

1. Missing Filename
2. AUDIODEV device not recognized
3. Instant crashes on setting the encoder with "-e"

Number one started working after I replaced the "wav" paremeter with "waveaudio"
Number two was fixed by using numbers (from 0 to ...) instead of the names of the devices
Number three was fixed by adding / using the option {shell : true}

Now new problems arrive by using shell: true => The process doesn't get killed. Leaving {encoding: `binary`} as an option also makes that process invisible for me & only killing the whole node app stopped the recording.

After sending the kill command the recorded file also starts to "bloat" (20 s of recording with killing it immediately results in a ~ 5 mb file whilst 20s of recording + waiting 10s to kill the process resulted in a 40mb file).

I have no idea what factors decide the encoding setting (both the parameter for sox and the node childProcess), so I left it as in your module. I also have no idea what sox is piping out.

I also don't know how I would be able to make the sox filestream readable on a client machine.

´´´js
childProcess = processSpawn(
    'sox',
    [
      '-q',
      '-c 2',
      '-r 48000',
      '-t',
      'waveaudio',
      '0',
      '-V0',
      '-L',
      '-b 16',
      '-e signed-integer',
      'F:/temp/example.wav'
    ],
    { encoding: `binary`, shell: true }
  );
  childProcess.on('close', (code, signal) => {
    console.log(code, signal);
  });
  setTimeout(() => {
      childProcess.kill('SIGTERM'); //I've used different "kill messages" suggested on so
      console.log('process killed');
  }, 20000)
´´´

Summary of the questions : 

1. How can I kill the childProcess if I set shell to true
2. What are / how to decide on the encoding settings for sox & node
3. How to send the sox datastream to a client 
(4.  What are the -L and the -b 16 flags / what do they mean)

**Comment by RedKenrok** [comment]
I see you are trying to directly spawn your own child process without using the library, therefore I first and foremost recommend looking at the source code of the repository to get a better idea of how it works. (See: https://github.com/RedKenrok/node-audiorecorder/blob/master/library/index.js) Secondly this module is quite similar to the node-record-lpcm16 module so do checkout its source code as well for a second opinion. (See: https://github.com/gillesdemey/node-record-lpcm16/blob/master/index.js)

But let us move on to your questions. It has been a while since I worked on this as well as I am not the most proficient with this stuff, however I will do my best to answer your questions.

1. Do note when no argument is given the `SIGTERM` options is assumed by default (See: [nodejs docs on child_process](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal). For me using the default has worked fine because I am not using the shell option.  But my understanding of the issue is that you are killing the shell process and not the shell's child process. Perhaps the [tree-kill](https://www.npmjs.com/package/tree-kill) module can be useful to you, although I haven't used it myself it looks promising enough.

2. This is completely based on your needs. Which is difficult to answer for you. I would recommend doing further research yourself in how encoding changes your audio file.

3. If you call `childProcess.stdout` (might not work in combination with `shell: true`, experiment with this yourself) you simply get the data stream of the child process and can use it from there on out however you need. (See [Node.js's docs about streams](https://nodejs.org/api/stream.html)).

4. For more information of what each flag does see the [SoX documentation](http://sox.sourceforge.net/sox.html).

The SoX documentation reads the following for the `−b` option `The number of bits (a.k.a. bit-depth or sometimes word-length) in each encoded sample. Not applicable to complex encodings such as MP3 or GSM. Not necessary with encodings that have a fixed number of bits, e.g. A/μ-law, ADPCM.`

The SoX documentation read the following for the `−L, −B, −x` flags: `These options specify whether the byte-order of the audio data is, respectively, ‘little endian’, ‘big endian’, or the opposite to that of the system on which SoX is being used. Endianness applies only to data encoded as floating-point, or as signed or unsigned integers of 16 or more bits. It is often necessary to specify one of these options for headerless files, and sometimes necessary for (otherwise) self-describing files. A given endian-setting option may be ignored for an input file whose header contains a specific endianness identifier, or for an output file that is actually an audio device.`

I hope this has been of some use. Kind regards, Ron.

**Comment by Twiggeh** [comment]
Tree kill helped out with the termination :) 

The pid reported by node (childProcess.pid) was pointing to something else : 
![issue no 1](https://user-images.githubusercontent.com/23149166/71560099-bf6ee200-2a65-11ea-964e-81608af15f78.PNG)

I'll read up on on the docs. Thank you for your help and I wish you a happy new year :)

**Comment by RedKenrok** [comment]
I'm glad I was able to help, best of luck, and happy new year to you as well!
