### ISSUE TITLE
Use of device option in constructor

### ISSUE THREAD

**Issue by joshkmartinez** [RedKenrok/node-audiorecorder#18]
I'm having a little trouble figuring out how to change my recording device.
These are my audio devices:
```
system_profiler SPAudioDataType -detailLevel mini

Audio:

    Devices:

        Joshua’s AirPods:

          Default Input Device: Yes
          Input Channels: 1
          Manufacturer: 4c
          Current SampleRate: 16000
          Transport: Bluetooth
          Input Source: Default

        Joshua’s AirPods:

          Default Output Device: Yes
          Default System Output Device: Yes
          Manufacturer: 4c
          Output Channels: 2
          Current SampleRate: 48000
          Transport: Bluetooth
          Output Source: Default

        Built-in Microphone:

          Input Channels: 2
          Manufacturer: Apple Inc.
          Current SampleRate: 44100
          Transport: Built-in
          Input Source: Internal Microphone

        Built-in Output:

          Manufacturer: Apple Inc.
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Built-in
          Output Source: Internal Speakers

        Background Music:

          Input Channels: 2
          Manufacturer: Background Music contributors
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Virtual
          Input Source: Default
          Output Source: Default

        Background Music (UI Sounds):

          Input Channels: 2
          Manufacturer: Background Music contributors
          Output Channels: 2
          Current SampleRate: 44100
          Transport: Virtual
          Input Source: Default
          Output Source: Default
```
Say I'd like to explicitly set my AirPods as the recording device. This is my constructor
```js
const audioRecorder = new AudioRecorder({
    program: process.platform === 'win32' ? 'sox' : 'rec',
    device: '"Joshua\'s AirPods"',
	silence: 0
}, console);
```
I'm having trouble figureing out how to format the device name, would it be like `device: '"Joshua\'s AirPods"'` or ` device: "Joshua's AirPods"`?
This is the command generated:
```
rec -q -c 1 -r 16000 -t wav -d "Joshua's AirPods" -V0 -L -b 16 -e signed-integer -
```
AudioRecorder exits with code 1 either way I try it. If I don't format it with quotes the device name seems to be taken as separate arguments, and the same thing happens if I do format it with quotes.  
This probably is trivial, but how do I format the device name when I pass it to the constructor? 

I'm using `node-audiorecorder` v1.4.2
*I don't have this problem when I don't define a device

**Comment by RedKenrok** [comment]
It works when you don't define a device since the airpods are as the default in the operating system, which I assume to be MacOS. I myself run Windows 10 and can therefore not replicate the exact issue. That being said I'll do my best anyway, in order to do so I still have a couple questions first.
1. What version of `sox/rec` do you have installed?
2. When you don't specify an exact device what is the command that gets generated? Would love to know the difference since that does work.

**Comment by joshkmartinez** [comment]
Thanks for the response
I'm using sox 14.2.2
Without a device defined the command is `rec -q -c 1 -r 16000 -t wav -V0 -L -b 16 -e signed-integer -`

**Comment by RedKenrok** [comment]
From the looks of it I seem to have interpreted the documentation wrong when writing this module. Because the flag `-d` is used to specify the default audio device should be used. Which not required when the `rec` command is used. The SoX docs read the following:

---

Some systems provide more than one type of (SoX-compatible) audio driver, e.g. ALSA & OSS, or SUNAU & AO. Systems can also have more than one audio device (a.k.a. ‘sound card’). If more than one audio driver has been built-in to SoX, and the default selected by SoX when recording or playing is not the one that is wanted, then the AUDIODRIVER environment variable can be used to override the default. For example (on many systems):
```
   set AUDIODRIVER=oss
   play ...
```
The AUDIODEV environment variable can be used to override the default audio device, e.g.
```
   set AUDIODEV=/dev/dsp2
   play ...
   sox ... −t oss
```
or
```
   set AUDIODEV=hw:soundwave,1,2
   play ...
   sox ... −t alsa
```

---

So unfortunately it seem you need to run a different command to specify another device besides the default. For more information about SoX see the official documentation at: http://sox.sourceforge.net/sox.html, or run the `man sox` command in your terminal.
