### ISSUE TITLE
Have you considered integrating pocketsphinx.js?

### ISSUE THREAD

**Issue by jaxcore** [RedKenrok/node-audiorecorder#8]
This project looks great btw.

I am thinking about using your audiorecorder code to pipe the audio stream into pocketsphinx.js 

https://github.com/syl22-00/pocketsphinx.js

That way we can do 100% client-side voice recognition with real-time voice visualization inside an Electron app which would be terrific for a lot of voice projects.  There's just so few (maybe no) voice libraries out there that get this right, everything uses the Web Audio API for microphone access which is just so flakey, slow, and relies on Google :( and it doesn't even work for me inside an Electron app at the moment.

If you pipe your audiorecorder data in as described here 5 years ago it might work reasonably well:

https://github.com/syl22-00/pocketsphinx.js/issues/2

I'm not great with audio processing but I am seriously thinking about doing this because something like this is really badly needed even if it's not super accurate.

Before I go down this rabbit hole, do you think it would work?

**Comment by RedKenrok** [comment]
Sorry for the delayed response. I am unsure whether you are asking how you might integrate PocketSphinx.js into your project, or if I could add speech recognition into this node module. To answer the latter, no, since this module is aimed at audio recording not audio processing.

In terms of how you could implement this audio recording module alongside PocketSphinx.js in Electron there does not seem to be a need. PocketSphinx.js already has its own build-in audio recorder referred to as `audioRecorder.js` which can be used in the browser. I would recommend you read the [PocketSphinx.js's README.md](https://github.com/syl22-00/pocketsphinx.js#readme) and [PocketSphinx.js's Audio Recorder README.md](https://github.com/syl22-00/pocketsphinx.js/tree/master/doc/AudioRecorder) thoroughly.

I hope this information has been of use to you, and best of luck.

Kind regards,
Ron Dekker

**Comment by jaxcore** [comment]
Thanks for the response.  I was mainly just curious if you, or maybe someone else had written such an integration - I don't want to reinvent the wheel unless necessary.  But unfortunately PocketSphinx.js records the sound using Web Speech API in a browser, which for a variety of reasons I don't want to do.  And I can't find any open source project that combines voice recording (outside a browser) and voice recognition (in a browser) libraries together.

**Comment by RedKenrok** [comment]
I'm afraid I won't be able to help you further with that, since the only solutions I have pursued utilize web API's like Wit.ai or Google Speech API.
